### PR TITLE
BUG: Creating personal schedule fails first try until quarter field changed

### LINKED ISSUE #7: BUG: Creating personal schedule fails first try until quarter field changed
### Summary

Creating personal schedule fails on the first attempt until quarter field is changed.
It gives a toast: "Error: undefined"

### Expected Behavior

Creation works even with default selected quarter.

### Current / Observed Behavior

See above

### Steps to Reproduce

See above

### Browser / Platform Info

_No response_

### PR DESCRIPTION
**Pull request by mucucsb**
In this pr, I resolved the bug where personal schedule is failing before the quarter field is changed.

Dokku Link: https://proj-courses-mu.dokku-11.cs.ucsb.edu/

Test in incognito mode as this should reset the localstorage. Click on "Personal Schedules," select "Add Schedule," and enter a name and description but click "create" without changing the quarter. 

close #7

### CODE REVIEW

**Review by ThatsBadJuju — APPROVED** [review]
Tested bugfix on dokku deployment, LGTM

File: frontend/src/main/components/Quarters/SingleQuarterDropdown.js [hunk 1]
```diff
@@ -20,6 +20,9 @@ function SingleQuarterDropdown({
   onChange = null,
   label = "Quarter",
 }) {
+  if (localStorage.getItem("PersonalScheduleForm-quarter") == null) {
+    localStorage.setItem("PersonalScheduleForm-quarter", quarters[0].yyyyq);
```
Comment (chriscerie) [inline frontend/src/main/components/Quarters/SingleQuarterDropdown.js:24]: Components cannot have side effects during render. For more discussion on this see https://github.com/ucsb-cs156-f23/proj-courses-f23-7pm-4/pull/26#discussion_r1401336976

**Review by chriscerie — CHANGES_REQUESTED** [review]

**Review by pconrad — APPROVED** [review]
LGTM
